stages:
  unpack_to_raw:
    cmd: python build/unpack_to_raw.py --input_dir ./data/raw --bucket_name raw --output_file_name combined_raw.csv
    deps:
      - build/unpack_to_raw.py

  preprocess_to_staging:
    cmd: python src/preprocess_to_staging.py --bucket_raw raw --input_file combined_raw.csv --db_host 127.0.0.1 --db_user root --db_password root --db_name staging
    deps:
      - src/preprocess_to_staging.py

  process_to_curated:
    cmd: python src/process_to_curated.py --db_host 127.0.0.1 --db_user root --db_password root --db_name staging --mongo_host localhost --mongo_port 27017
    deps:
      - src/process_to_curated.py